# Generated by Django 3.0.8 on 2020-08-18 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='delivered_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='estimated_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('S', 'submitted'), ('D', 'delivered'), ('C', 'canceled')], default='submitted', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
