# Generated by Django 3.0.8 on 2020-08-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200818_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('S', 'submitted'), ('D', 'delivered'), ('C', 'canceled')], default='S', max_length=1),
        ),
    ]
